CREATE TABLE IF NOT EXISTS order_rejections (
  id SERIAL PRIMARY KEY,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  rider_id INTEGER REFERENCES riders(id) ON DELETE CASCADE,
  rejected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);